import { PrismaClient } from '@prisma/client'; // Import Prisma Client

const prisma = new PrismaClient(); // Initialize Prisma Client

/**
 * Creates a new amenity in the database.
 * @param {string} name - The name of the new amenity.
 */
const createAmenity = async (name) => {
  try {
    // ✅ Validate required fields
    if (!name) {
      console.warn(`⚠️ Validation Failed: Amenity name is required.`);

      // ✅ Fix: Ensure validation errors return 400
      const validationError = new Error('Amenity name is required.');
      validationError.statusCode = 400;
      throw validationError;
    }

    // Create a new amenity (ID is auto-generated by Prisma)
    const newAmenity = await prisma.amenity.create({
      data: { name },
    });

    console.log('✅ New amenity created:', newAmenity); // Debug log
    return newAmenity; // Return the newly created amenity
  } catch (error) {
    console.error('❌ Error creating amenity:', error.message);

    // ✅ Fix: Assign `statusCode = 400` for known validation errors
    if (!error.statusCode) error.statusCode = 500;
    
    throw error;
  }
};

export default createAmenity;


